name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4, 2026-07-16

      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27, 2024-05-15
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes auto-allocate-uids cgroups
            auto-allocate-uids = true

      - name: nix flake check
        run: nix flake check -L
